apiVersion: v1
kind: ReplicationController
metadata:
  name: kubia # rc 이름
spec:
  replicas: 3 # 의도하는 파드 인스턴스 수
  selector:
    app: kubia # 파드 셀렉터(레이블 셀렉터)로 rc가 관리하는 파드 선택
  template: # 새 파드에 사용할 파드 템플릿
    metadata:
      labels:
        app: kubia
    spec:
      containers:
      - name: kubia
        image: luksa/kubia
        ports:
        - containerPort: 8080
